version: '3'
services:
    dev:
        image: node:11
        volumes:
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: npm run dev
        ports:
            - 1234:1234
            - 3000:3000
    mongodb:
        command: mongod
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db

volumes:
    mongodata:
