version: '3'
services:
    api:
        container_name: api
        image: node:13
        volumes:
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: npm run devInspect
        ports:
            - 1234:1234
            - 3005:3000
            - 9229:9229
    mongodb:
        command: mongod
        container_name: mongodb
        environment:
            - MONGO_DATA_DIR=/data/db
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodata:/data/db
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: lists
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8087:8080

volumes:
    mongodata:
    pgdata:
