version: '3'
services:
    api:
        container_name: api
        image: node:13
        volumes:
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: npm run dev
        ports:
            - 1234:1234
            - 3005:3000
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: lists
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8087:8080

volumes:
    pgdata: