version: '3'
services:
    api:
        container_name: api
        image: node:13
        volumes:
            - .:/usr/src/service
        working_dir: /usr/src/service
        command: npm run devInspect
        ports:
            - 1234:1234
            - 3005:3000
            - 9229:9229
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: lists
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        logging:
            driver: none
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-lixpi@lixpi.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-lixpi}
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped

volumes:
    pgdata:
